### PR TITLE
Fix multiple issues introduced by database merge

### LINKED ISSUE #415: Disable database doesn't work as expected
In some edge cases, the database is still accessed.

### LINKED ISSUE #416: Incorrect validation of health points
Health points are required to be integers, which is incorrect. They are only numbers.

### PR DESCRIPTION
**Pull request by ClFeSc**
Closes #415 
Closes #416

### CODE REVIEW

File: backend/src/exercise/exercise-wrapper.ts [hunk 1]
```diff
@@ -370,7 +370,7 @@ export class ExerciseWrapper extends NormalType<
 
     public async getTimeLine(): Promise<ExerciseTimeline> {
         const completeHistory = [
-            ...(this.id !== undefined
+            ...(this.id && Config.useDb
```
Comment (Dassderdie) [inline backend/src/exercise/exercise-wrapper.ts:373]:
```suggestion
            ...(this.id !== undefined && Config.useDb
```

**Review by Dassderdie — APPROVED** [review]
I haven't tested it out. But code lgtm
