### PR TITLE
Fix transport progress report with no regions

### LINKED ISSUE #1103: Requesting transfer progress crashes reducer if no regions are managed
There is an error in the backend, pausing the exercise, when adding a "Transportorganisation" behavior to a patient tray:

```
TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at Object.handleEvent (/.../digital-fuesim-manv/shared/src/simulation/behaviors/manage-patient-transport-to-hospital.ts:459:31)
    at <anonymous> (/.../digital-fuesim-manv/shared/src/simulation/utils/simulation.ts:57:62)
    at Proxy.forEach (<anonymous>)
    at <anonymous> (/.../digital-fuesim-manv/shared/src/simulation/utils/simulation.ts:56:34)
    at Proxy.forEach (<anonymous>)
    at handleSimulationEvents (/.../digital-fuesim-manv/shared/src/simulation/utils/simulation.ts:55:31)
    at simulateSingleRegion (/.../digital-fuesim-manv/shared/src/simulation/utils/simulation.ts:25:5)
    at <anonymous> (/.../digital-fuesim-manv/shared/src/simulation/utils/simulation.ts:15:9)
    at Array.forEach (<anonymous>)
```

Reproduction:

1. Create a new exercise.
2. Start it.
3. Add a new patient tray.
4. Add the "Transportorganisation" behavior to it via the "Übungsleitung" overview of the patient tray.
5. Go to the "Funker" overview of the patient tray.
6. Request information "Transportfortschritt für von hier verwaltete Bereiche" (Hotkey `B`).
7. Observe the exercise pausing with the provided trace in the backend's console.

_Originally posted by @ClFeSc in https://github.com/hpi-sam/digital-fuesim-manv/issues/1076#issuecomment-3215192703_

### PR DESCRIPTION
**Pull request by lukasrad02**
### PR Checklist

Please make sure to fulfil the following conditions before marking this PR ready for review:

- [x] If this PR adds or changes features or fixes bugs, this has been added to the changelog
- [x] If this PR adds new actions or other ways to alter the state, [test scenarios](https://github.com/hpi-sam/digital-fuesim-manv-public-test-scenarios) have been added.
- [x] I have the right to license the code submitted with this Pull Request under the mentioned license in the file [LICENSE-README.md](LICENSE-README.md) (i.e., this is my
      own code or code licensed under a license compatible to AGPL v3.0 or later, for exceptions look into [LICENSE-README.md](LICENSE-README.md)) and
      hereby license the code in this Pull Request under it.
      I certify that by signing off my commits (see In case of using third party code, I have given appropriate credit.
      We are using DCO for that, see [here](https://github.com/dcoapp/app#how-it-works) for more information.
- [x] If I have used third party code and I mentioned it in the code, I also updated the [inspired-by-or-copied-from-list.html](inspired-by-or-copied-from-list.html) list to include the links.

### CODE REVIEW

File: shared/src/simulation/behaviors/manage-patient-transport-to-hospital.ts [hunk 1]
```diff
@@ -456,7 +456,14 @@ export const managePatientTransportToHospitalBehavior: SimulationBehavior<Manage
                                 );
                             const expectedManagedPatients = Object.values(
                                 expectedPatientsPerRegion
-                            ).reduce(addResourceDescription);
+                            ).reduce(addResourceDescription, {
```
Comment (ClFeSc) [inline shared/src/simulation/behaviors/manage-patient-transport-to-hospital.ts:459]: Nice, the [note about `Array.prototype.reduce` throwing an error when no `initialValue` is specified and the array is empty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce#exceptions) is missing from the [TS docstring](https://github.com/microsoft/TypeScript/blob/main/src/lib/es5.d.ts#L1465-L1471). (Resolve this to merge.)

**Review by ClFeSc — APPROVED** [review]
I don't know why the auditing fails, but I think we can ignore it.
