### PR TITLE
Remove all `...` where they may lead to problems with too many arguments

### LINKED ISSUE #451: Backend in container fails after a while
Found this in the logs on the feature/395-tragetrupps-carrying-unit branch, that was used for BABZ
<details>
  <summary>docker compose logs --tail=200 digital-fuesim-manv-exp</summary>

```
digital-fuesim-manv-exp  | (Use `node --trace-warnings ...` to show where the warning was created)
digital-fuesim-manv-exp  | query: SELECT * FROM current_schema()
digital-fuesim-manv-exp  | query: CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
digital-fuesim-manv-exp  | query: SHOW server_version;
digital-fuesim-manv-exp  | query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'migrations'
digital-fuesim-manv-exp  | query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'typeorm_metadata'
digital-fuesim-manv-exp  | query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
digital-fuesim-manv-exp  | No migrations are pending
digital-fuesim-manv-exp  | (node:49) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
digital-fuesim-manv-exp  | (Use `node --trace-warnings ...` to show where the warning was created)
digital-fuesim-manv-exp  | Successfully connected to the database.
digital-fuesim-manv-exp  | Loading exercises from database…
digital-fuesim-manv-exp  | ❌ An error occurred while loading exercises.
digital-fuesim-manv-exp  | file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:250
digital-fuesim-manv-exp  |                 exercise.temporaryActionHistory.splice(0, exercise.temporaryActionHistory.length, ...(await databaseService.actionWrapperService.getFindAll({
digital-fuesim-manv-exp  |                                                 ^
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | RangeError: Maximum call stack size exceeded
digital-fuesim-manv-exp  |     at file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:250:49
digital-fuesim-manv-exp  |     at runMicrotasks (<anonymous>)
digital-fuesim-manv-exp  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
digital-fuesim-manv-exp  |     at async Promise.all (index 23)
digital-fuesim-manv-exp  |     at async file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:247:31
digital-fuesim-manv-exp  |     at async EntityManager.transaction (/usr/local/app/backend/node_modules/typeorm/entity-manager/EntityManager.js:72:28)
digital-fuesim-manv-exp  |     at async main (file:///usr/local/app/backend/dist/src/index.js:31:31)
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | > digital-fuesim-manv-backend@0.0.0 migration:run:prod
digital-fuesim-manv-exp  | > npm run typeorm:cli:prod migration:run
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
digital-fuesim-manv-exp  |   errno: -13,
digital-fuesim-manv-exp  |   code: 'EACCES',
digital-fuesim-manv-exp  |   syscall: 'scandir',
digital-fuesim-manv-exp  |   path: '/root/.npm/_logs'
digital-fuesim-manv-exp  | }
digital-fuesim-manv-exp  | npm WARN logfile Error: EACCES: permission denied, scandir '/root/.npm/_logs'
digital-fuesim-manv-exp  | npm WARN logfile  error cleaning log files [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
digital-fuesim-manv-exp  | npm WARN logfile   errno: -13,
digital-fuesim-manv-exp  | npm WARN logfile   code: 'EACCES',
digital-fuesim-manv-exp  | npm WARN logfile   syscall: 'scandir',
digital-fuesim-manv-exp  | npm WARN logfile   path: '/root/.npm/_logs'
digital-fuesim-manv-exp  | npm WARN logfile }
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | > digital-fuesim-manv-backend@0.0.0 typeorm:cli:prod
digital-fuesim-manv-exp  | > NODE_ENV=migration node --experimental-specifier-resolution=node ./node_modules/typeorm/cli -d dist/src/database/migration-datasource.js "migration:run"
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | (node:38) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
digital-fuesim-manv-exp  | (Use `node --trace-warnings ...` to show where the warning was created)
digital-fuesim-manv-exp  | query: SELECT * FROM current_schema()
digital-fuesim-manv-exp  | query: CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
digital-fuesim-manv-exp  | query: SHOW server_version;
digital-fuesim-manv-exp  | query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'migrations'
digital-fuesim-manv-exp  | query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'typeorm_metadata'
digital-fuesim-manv-exp  | query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
digital-fuesim-manv-exp  | No migrations are pending
digital-fuesim-manv-exp  | (node:49) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
digital-fuesim-manv-exp  | (Use `node --trace-warnings ...` to show where the warning was created)
digital-fuesim-manv-exp  | Successfully connected to the database.
digital-fuesim-manv-exp  | Loading exercises from database…
digital-fuesim-manv-exp  | ❌ An error occurred while loading exercises.
digital-fuesim-manv-exp  | file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:250
digital-fuesim-manv-exp  |                 exercise.temporaryActionHistory.splice(0, exercise.temporaryActionHistory.length, ...(await databaseService.actionWrapperService.getFindAll({
digital-fuesim-manv-exp  |                                                 ^
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | RangeError: Maximum call stack size exceeded
digital-fuesim-manv-exp  |     at file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:250:49
digital-fuesim-manv-exp  |     at runMicrotasks (<anonymous>)
digital-fuesim-manv-exp  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
digital-fuesim-manv-exp  |     at async Promise.all (index 23)
digital-fuesim-manv-exp  |     at async file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:247:31
digital-fuesim-manv-exp  |     at async EntityManager.transaction (/usr/local/app/backend/node_modules/typeorm/entity-manager/EntityManager.js:72:28)
digital-fuesim-manv-exp  |     at async main (file:///usr/local/app/backend/dist/src/index.js:31:31)
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | > digital-fuesim-manv-backend@0.0.0 migration:run:prod
digital-fuesim-manv-exp  | > npm run typeorm:cli:prod migration:run
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
digital-fuesim-manv-exp  |   errno: -13,
digital-fuesim-manv-exp  |   code: 'EACCES',
digital-fuesim-manv-exp  |   syscall: 'scandir',
digital-fuesim-manv-exp  |   path: '/root/.npm/_logs'
digital-fuesim-manv-exp  | }
digital-fuesim-manv-exp  | npm WARN logfile Error: EACCES: permission denied, scandir '/root/.npm/_logs'
digital-fuesim-manv-exp  | npm WARN logfile  error cleaning log files [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
digital-fuesim-manv-exp  | npm WARN logfile   errno: -13,
digital-fuesim-manv-exp  | npm WARN logfile   code: 'EACCES',
digital-fuesim-manv-exp  | npm WARN logfile   syscall: 'scandir',
digital-fuesim-manv-exp  | npm WARN logfile   path: '/root/.npm/_logs'
digital-fuesim-manv-exp  | npm WARN logfile }
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | > digital-fuesim-manv-backend@0.0.0 typeorm:cli:prod
digital-fuesim-manv-exp  | > NODE_ENV=migration node --experimental-specifier-resolution=node ./node_modules/typeorm/cli -d dist/src/database/migration-datasource.js "migration:run"
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | (node:38) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
digital-fuesim-manv-exp  | (Use `node --trace-warnings ...` to show where the warning was created)
digital-fuesim-manv-exp  | query: SELECT * FROM current_schema()
digital-fuesim-manv-exp  | query: CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
digital-fuesim-manv-exp  | query: SHOW server_version;
digital-fuesim-manv-exp  | query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'migrations'
digital-fuesim-manv-exp  | query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'typeorm_metadata'
digital-fuesim-manv-exp  | query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
digital-fuesim-manv-exp  | No migrations are pending
digital-fuesim-manv-exp  | (node:49) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
digital-fuesim-manv-exp  | (Use `node --trace-warnings ...` to show where the warning was created)
digital-fuesim-manv-exp  | Successfully connected to the database.
digital-fuesim-manv-exp  | Loading exercises from database…
digital-fuesim-manv-exp  | ❌ An error occurred while loading exercises.
digital-fuesim-manv-exp  | file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:250
digital-fuesim-manv-exp  |                 exercise.temporaryActionHistory.splice(0, exercise.temporaryActionHistory.length, ...(await databaseService.actionWrapperService.getFindAll({
digital-fuesim-manv-exp  |                                                 ^
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | RangeError: Maximum call stack size exceeded
digital-fuesim-manv-exp  |     at file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:250:49
digital-fuesim-manv-exp  |     at runMicrotasks (<anonymous>)
digital-fuesim-manv-exp  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
digital-fuesim-manv-exp  |     at async Promise.all (index 23)
digital-fuesim-manv-exp  |     at async file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:247:31
digital-fuesim-manv-exp  |     at async EntityManager.transaction (/usr/local/app/backend/node_modules/typeorm/entity-manager/EntityManager.js:72:28)
digital-fuesim-manv-exp  |     at async main (file:///usr/local/app/backend/dist/src/index.js:31:31)
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | > digital-fuesim-manv-backend@0.0.0 migration:run:prod
digital-fuesim-manv-exp  | > npm run typeorm:cli:prod migration:run
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
digital-fuesim-manv-exp  |   errno: -13,
digital-fuesim-manv-exp  |   code: 'EACCES',
digital-fuesim-manv-exp  |   syscall: 'scandir',
digital-fuesim-manv-exp  |   path: '/root/.npm/_logs'
digital-fuesim-manv-exp  | }
digital-fuesim-manv-exp  | npm WARN logfile Error: EACCES: permission denied, scandir '/root/.npm/_logs'
digital-fuesim-manv-exp  | npm WARN logfile  error cleaning log files [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
digital-fuesim-manv-exp  | npm WARN logfile   errno: -13,
digital-fuesim-manv-exp  | npm WARN logfile   code: 'EACCES',
digital-fuesim-manv-exp  | npm WARN logfile   syscall: 'scandir',
digital-fuesim-manv-exp  | npm WARN logfile   path: '/root/.npm/_logs'
digital-fuesim-manv-exp  | npm WARN logfile }
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | > digital-fuesim-manv-backend@0.0.0 typeorm:cli:prod
digital-fuesim-manv-exp  | > NODE_ENV=migration node --experimental-specifier-resolution=node ./node_modules/typeorm/cli -d dist/src/database/migration-datasource.js "migration:run"
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | (node:38) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
digital-fuesim-manv-exp  | (Use `node --trace-warnings ...` to show where the warning was created)
digital-fuesim-manv-exp  | query: SELECT * FROM current_schema()
digital-fuesim-manv-exp  | query: CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
digital-fuesim-manv-exp  | query: SHOW server_version;
digital-fuesim-manv-exp  | query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'migrations'
digital-fuesim-manv-exp  | query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = 'public' AND "table_name" = 'typeorm_metadata'
digital-fuesim-manv-exp  | query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
digital-fuesim-manv-exp  | No migrations are pending
digital-fuesim-manv-exp  | (node:49) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
digital-fuesim-manv-exp  | (Use `node --trace-warnings ...` to show where the warning was created)
digital-fuesim-manv-exp  | Successfully connected to the database.
digital-fuesim-manv-exp  | Loading exercises from database…
digital-fuesim-manv-exp  | ❌ An error occurred while loading exercises.
digital-fuesim-manv-exp  | file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:250
digital-fuesim-manv-exp  |                 exercise.temporaryActionHistory.splice(0, exercise.temporaryActionHistory.length, ...(await databaseService.actionWrapperService.getFindAll({
digital-fuesim-manv-exp  |                                                 ^
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | RangeError: Maximum call stack size exceeded
digital-fuesim-manv-exp  |     at file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:250:49
digital-fuesim-manv-exp  |     at runMicrotasks (<anonymous>)
digital-fuesim-manv-exp  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
digital-fuesim-manv-exp  |     at async Promise.all (index 23)
digital-fuesim-manv-exp  |     at async file:///usr/local/app/backend/dist/src/exercise/exercise-wrapper.js:247:31
digital-fuesim-manv-exp  |     at async EntityManager.transaction (/usr/local/app/backend/node_modules/typeorm/entity-manager/EntityManager.js:72:28)
digital-fuesim-manv-exp  |     at async main (file:///usr/local/app/backend/dist/src/index.js:31:31)
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | > digital-fuesim-manv-backend@0.0.0 migration:run:prod
digital-fuesim-manv-exp  | > npm run typeorm:cli:prod migration:run
digital-fuesim-manv-exp  |
digital-fuesim-manv-exp  | glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
digital-fuesim-manv-exp  |   errno: -13,
digital-fuesim-manv-exp  |   code: 'EACCES',
digital-fuesim-manv-exp  |   syscall: 'scandir',
digital-fuesim-manv-exp  |   path: '/root/.npm/_logs'
digital-fuesim-manv-exp  | }
```
</details>

The container is still running, but the backend does not work anymore.
Also the normal dev container is in mode `restarting`:

<details>
  <summary>dev container, message repeating itself_</summary>

```
digital-fuesim-manv-dev  |
digital-fuesim-manv-dev  | > digital-fuesim-manv-backend@0.0.0 migration:run:prod
digital-fuesim-manv-dev  | > npm run typeorm:cli:prod migration:run
digital-fuesim-manv-dev  |
digital-fuesim-manv-dev  |
```
</details>

### PR DESCRIPTION
**Pull request by ClFeSc**
Closes #451

### CODE REVIEW

File: backend/src/utils/array.ts [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+    elements.forEach((element) => array.push(element));
+    return array;
+}
+
+/**
+ * Make the provided {@link array} empty and return it.
+ * @param array The array to make empty (in-place)
+ * @returns The emptied array
+ */
+export function removeAll<T>(array: T[]): T[] {
```
Comment (Dassderdie) [inline backend/src/utils/array.ts:17]:
```suggestion
export function removeAll<T>(array: T[]): void {
```

File: backend/src/utils/array.ts [hunk 2]
```diff
@@ -0,0 +1,20 @@
+/**
+ * Add all {@link elements} to {@link array}. This mutates {@link array} and returns it.
+ * @param array The array to append to
+ * @param elements The elements to append
+ * @returns The appended array
+ */
+export function pushAll<T>(array: T[], elements: T[]): T[] {
```
Comment (Dassderdie) [inline backend/src/utils/array.ts:7]:
```suggestion
export function pushAll<T>(array: T[], elements: T[]): void {
```

Change the return type to `void`, to make sure the programmer knows this mutates the original array instead of returning a new array.

File: backend/src/utils/array.ts [hunk 3]
```diff
@@ -0,0 +1,20 @@
...
+    elements.forEach((element) => array.push(element));
```
Comment (Dassderdie) [inline backend/src/utils/array.ts:8]: Add a comment about `.push(...Array(300000).fill(1))` causing a memory error (because all elements are loaded to the stack).

**Review by Dassderdie — CHANGES_REQUESTED** [review]
See comments. The general approach is fine with me.

File: backend/src/utils/array.ts [hunk 4]
```diff
@@ -0,0 +1,18 @@
+/**
+ * Add all {@link elements} to {@link array}. This mutates {@link array}.
+ * @param array The array to append to
+ * @param elements The elements to append
+ *
+ * @remark Use this where something like `.push(...Array(300000).fill(1))` is possible.
+ */
+export function pushAll<T>(array: T[], elements: T[]): void {
+    elements.forEach((element) => array.push(element));
+}
```
Comment (Dassderdie) [inline backend/src/utils/array.ts:10]:
```suggestion
 * @remark You can't use `myArray.push(...elementsToBeAdded)` if `elementsToBeAdded` could have more than ca. 130,000 elements, because there is a maximum number of function parameters (based in the stack size). This function works with such big arrays too.
 */
export function pushAll<T>(array: T[], elements: T[]): void {
    elements.forEach((element) => array.push(element));
}
```

**Review by Dassderdie — APPROVED** [review]
See my comment.
